
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define "mongodb-nodo1" do |machine|
    machine.vm.box = "kane_project/centos7gui"
    machine.vm.network "private_network", ip: "192.168.200.101"
    machine.vm.hostname = "mongodb-nodo1"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "mongodb-nodo1"
      vb.gui = true
      vb.memory = "2048"
    end
    machine.vm.provision :shell, inline: <<-SHELL
      sudo cp /vagrant/mongodb.repo /etc/yum.repos.d/
      sudo yum -y install mongodb-org
      sudo cp /vagrant/mongod-nodo1.conf /etc/mongod.conf
      sudo cp /vagrant/selinux.config /etc/selinux/config
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo setenforce 0
      sudo systemctl start mongod
      sudo systemctl enable mongod
    SHELL
  end
  config.vm.define "mongodb-nodo2" do |machine|
    machine.vm.box = "kane_project/centos7"
    machine.vm.network "private_network", ip: "192.168.200.102"
    machine.vm.hostname = "mongodb-nodo2"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "mongodb-nodo2"
      vb.gui = true
      vb.memory = "1024"
    end
    machine.vm.provision :shell, inline: <<-SHELL
      sudo cp /vagrant/mongodb.repo /etc/yum.repos.d/
      sudo yum -y install mongodb-org
      sudo cp /vagrant/mongod-nodo2.conf /etc/mongod.conf
      sudo cp /vagrant/selinux.config /etc/selinux/config
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo setenforce 0
      sudo systemctl start mongod
      sudo systemctl enable mongod
    SHELL
  end
  config.vm.define "mongodb-nodo3" do |machine|
    machine.vm.box = "kane_project/centos7"
    machine.vm.network "private_network", ip: "192.168.200.103"
    machine.vm.hostname = "mongodb-nodo3"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "mongodb-nodo3"
      vb.gui = true
      vb.memory = "1024"
    end
    machine.vm.provision :shell, inline: <<-SHELL
      sudo cp /vagrant/mongodb.repo /etc/yum.repos.d/
      sudo yum -y install mongodb-org
      sudo cp /vagrant/mongod-nodo3.conf /etc/mongod.conf
      sudo cp /vagrant/selinux.config /etc/selinux/config
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo setenforce 0
      sudo systemctl start mongod
      sudo systemctl enable mongod
      mongo 192.168.200.101:27017 /vagrant/enableReplicaSet.js
    SHELL
  end
  
end
