
Vagrant.configure("2") do |config|
  config.vm.box = "centos7gui"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "mongodb-standalone"
    vb.gui = true
    vb.memory = "2048"
  end
  config.vm.provision :shell do |shell|
    shell.inline = "sudo cp /vagrant/mongodb.repo /etc/yum.repos.d/"
  end
  config.vm.provision :shell do |shell|
    shell.inline = "sudo yum -y install mongodb-org"
  end
end
